# configuration file for social-media-listening

UKR:
  source: telegram
  channels:
    - "t.me/ukr_dopomoga"
    - "t.me/kramatorsk_help"
    - "t.me/kamyanetschat"
    - "t.me/drogobuch_vpo"
    - "t.me/KrasniyKut"
    - "t.me/Dopomoga_vzp"