# configuration file for social-media-listening

# Context and Extract
<country1>:
  country-code: <someISO3>
  channels-to-track:
  - <channel1>
  - <channel2>

<country2>:
  country-code: <someISO3>
  channels-to-track:
  - <channel1>
  - <channel2>