name: Update SML docker image in ACR

on:
  push:
    branches:
      - master
    
env:
  IMAGE_NAME: social-media-listening
  
jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log into registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest
        file: ./Dockerfile